### ISSUE TITLE
[Bug] Fivetran Facebook Ads Quickstart URL report missing creative IDs found in other tables

### ISSUE THREAD

**Issue by lp2485** [fivetran/dbt_github#54]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

ad_id's:
120208303477730366
120208329245030366

and creative_id's
120208334684140366
120208335843520366

are not syncing to facebook_ads__url_report
these records exist on the supporting tables for this report

### Relevant error log or model output

```shell
no errors
```

### Expected behavior

ad_id's:
120208303477730366
120208329245030366

and creative_id's
120208334684140366
120208335843520366

would sync to the facebook_ads__url_report table

### dbt Project configurations

Fivetran Facebook Ads Quickstart

### Package versions

Fivetran Facebook Ads Quickstart

### What database are you using dbt with?

bigquery

### dbt Version

Fivetran Facebook Ads Quickstart

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [X] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @lp2485 thanks for opening this issue. Would you actually be able to open a [Fivetran Support Ticket](https://support.fivetran.com/hc/en-us) for help with your above question. This repo is for our GitHub data model. Likewise, we have a repo for our [Facebook Ads data model](https://github.com/fivetran/dbt_facebook_ads), and I believe the main reason for the missing records is due to [this filter](https://github.com/fivetran/dbt_facebook_ads/blob/c1dad0c40fb22e44dfd992757bc73b954edc0bfa/models/facebook_ads__url_report.sql#L95) to remove any creatives without an associated url. 

If you could open the support ticket using the link above that would help direct you to the right place and will also allow us to more effectively investigate and triage your inquiry. Thanks!

**Comment by lp2485** [comment]
Support told me to open this ticket since they couldn't fix it

**Comment by fivetran-joemarkiewicz** [comment]
Thanks for the quick response and apologies for the mixed messaging. 

I was just able to find the Zendesk ticket where this was directed. It would actually be best to keep this conversation in that Support ticket. I just clued Ben in on keeping the conversation in the support ticket and I will take a look at the discrepancy your seeing there.

**Comment by fivetran-joemarkiewicz** [comment]
Marking this as wontfix and will close this issue as correspondence will continue within the previously opened Support ticket.

@lp2485 let me know if you have any questions. Thanks!
